"""Render + (optionally) commit a GitHub Actions workflow for agentprdiff.

The shape mirrors the snippet in the engine's AGENTS.md / README.md so an
adopter who switches to the CLI later sees the same workflow.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from git import GitCommandError, Repo

WORKFLOW_FILE = ".github/workflows/agentprdiff.yml"


def render(*, project_name: str, suite_globs: Iterable[str]) -> str:
    """Render the workflow YAML.

    ``suite_globs`` is an iterable of glob patterns (e.g. ``suites/*.py``).
    Defaults to the canonical ``suites/*.py`` if empty.
    """
    globs = list(suite_globs) or ["suites/*.py"]
    suite_args = " ".join(globs)
    return (
        "# Auto-generated by agentprdiff Studio.\n"
        f"# Project: {project_name}\n"
        "name: agentprdiff\n"
        "on:\n"
        "  pull_request:\n"
        "  push:\n"
        "    branches: [main]\n"
        "\n"
        "permissions:\n"
        "  contents: read   # least-privilege; GHAS flags workflows without this\n"
        "\n"
        "jobs:\n"
        "  agentprdiff:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v4\n"
        "\n"
        "      - uses: actions/setup-python@v5\n"
        "        with:\n"
        "          python-version: '3.11'\n"
        "\n"
        "      - name: Install project + agentprdiff\n"
        "        run: |\n"
        "          python -m pip install --upgrade pip\n"
        "          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi\n"
        "          pip install agentprdiff\n"
        "\n"
        "      - name: Check suites\n"
        "        env:\n"
        "          # Provide whichever your agents need.\n"
        "          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}\n"
        "          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}\n"
        "          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}\n"
        f"        run: agentprdiff check {suite_args} --json-out artifacts/agentprdiff.json\n"
        "\n"
        "      - uses: actions/upload-artifact@v4\n"
        "        if: always()\n"
        "        with:\n"
        "          name: agentprdiff\n"
        "          path: artifacts/\n"
    )


def commit_and_push(
    *,
    workspace: Path,
    content: str,
    token: str | None,
    author_name: str = "agentprdiff Studio",
    author_email: str = "studio@agentprdiff.local",
) -> dict:
    """Write the workflow file, commit it, and push to origin.

    Returns a small status dict: ``{path, committed: bool, pushed: bool, message}``.
    On any git failure we still return the dict — the caller surfaces the
    message to the user — rather than crash the request.

    Authentication: if the remote is HTTPS and a ``token`` is provided
    (Studio reads ``GIT_TOKEN`` from Secrets), we rewrite the remote URL
    in-memory to embed ``x-access-token:<token>@``. SSH remotes use the
    container's existing key material if present; we don't manage those.
    """
    target = workspace / WORKFLOW_FILE
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")

    try:
        repo = Repo(workspace)
    except Exception as exc:  # pragma: no cover — should never trigger on git intake
        return {"path": WORKFLOW_FILE, "committed": False, "pushed": False,
                "message": f"not a git repo: {exc}"}

    try:
        # Local commit author override so we don't depend on container git config.
        with repo.config_writer() as cfg:
            cfg.set_value("user", "name", author_name)
            cfg.set_value("user", "email", author_email)
        repo.index.add([WORKFLOW_FILE])
        if not repo.is_dirty(index=True, working_tree=False):
            return {"path": WORKFLOW_FILE, "committed": False, "pushed": False,
                    "message": "no changes to commit (file already present)"}
        repo.index.commit("Add agentprdiff CI workflow (via Studio)")
    except GitCommandError as exc:
        return {"path": WORKFLOW_FILE, "committed": False, "pushed": False,
                "message": f"commit failed: {exc}"}

    # Push.
    pushed = False
    push_msg = ""
    try:
        origin = repo.remotes.origin
        if token and origin.url.startswith("https://"):
            # In-memory rewrite. We don't persist the token-bearing URL.
            with origin.config_writer as cfg:  # type: ignore[attr-defined]
                pass  # noop; we use push_url override below
        push_kwargs = {}
        if token and origin.url.startswith("https://"):
            url_with_token = origin.url.replace(
                "https://", f"https://x-access-token:{token}@", 1
            )
            origin.set_url(url_with_token, push=True)
            try:
                origin.push()
                pushed = True
                push_msg = "pushed to origin"
            finally:
                # Restore the clean URL.
                origin.set_url(origin.url.replace(
                    f"x-access-token:{token}@", "", 1
                ), push=True)
        else:
            origin.push()
            pushed = True
            push_msg = "pushed to origin (no token; relied on ambient SSH/creds)"
    except GitCommandError as exc:
        push_msg = f"push failed: {exc}"
    except AttributeError:
        # No origin remote.
        push_msg = "no 'origin' remote configured"

    return {
        "path": WORKFLOW_FILE,
        "committed": True,
        "pushed": pushed,
        "message": push_msg or "ok",
    }
